Update IO.py
use ANSI  codec instead of ASCII, to avoid decide error such as:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 438: ordinal not in range(128)